module.exports = {
    important: true,
    theme: {
        fontFamily: {
            sans: [
                'Inter',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                '"Noto Sans"',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            mono: [
                'Operator Mono SSm A',
                'Operator Mono SSm B',
                'SFMono-Regular',
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
        },
        colors: {
            transparent: 'transparent',
            white: 'var(--white)',
            black: 'var(--black)',
            blue: {
                100: 'var(--blue-100)',
                200: 'var(--blue-200)',
                300: 'var(--blue-300)',
                400: 'var(--blue-400)',
                500: 'var(--blue-500)',
                600: 'var(--blue-600)',
                700: 'var(--blue-700)',
                800: 'var(--blue-800)',
                900: 'var(--blue-900)',
            },
            green: {
                100: 'var(--green-100)',
                200: 'var(--green-200)',
                300: 'var(--green-300)',
                400: 'var(--green-400)',
                500: 'var(--green-500)',
                600: 'var(--green-600)',
                700: 'var(--green-700)',
                800: 'var(--green-800)',
                900: 'var(--green-900)',
            },
            purple: {
                100: 'var(--purple-100)',
                200: 'var(--purple-200)',
                300: 'var(--purple-300)',
                400: 'var(--purple-400)',
                500: 'var(--purple-500)',
                600: 'var(--purple-600)',
                700: 'var(--purple-700)',
                800: 'var(--purple-800)',
                900: 'var(--purple-900)',
            },
            red: {
                100: 'var(--red-100)',
                200: 'var(--red-200)',
                300: 'var(--red-300)',
                400: 'var(--red-400)',
                500: 'var(--red-500)',
                600: 'var(--red-600)',
                700: 'var(--red-700)',
                800: 'var(--red-800)',
                900: 'var(--red-900)',
            },
            yellow: {
                100: 'var(--yellow-100)',
                200: 'var(--yellow-200)',
                300: 'var(--yellow-300)',
                400: 'var(--yellow-400)',
                500: 'var(--yellow-500)',
                600: 'var(--yellow-600)',
                700: 'var(--yellow-700)',
                800: 'var(--yellow-800)',
                900: 'var(--yellow-900)',
            },
            gray: {
                50: 'var(--gray-50)',
                100: 'var(--gray-100)',
                200: 'var(--gray-200)',
                300: 'var(--gray-300)',
                400: 'var(--gray-400)',
                500: 'var(--gray-500)',
                600: 'var(--gray-600)',
                700: 'var(--gray-700)',
                800: 'var(--gray-800)',
                900: 'var(--gray-900)',
            },
            tint: {
                50: 'var(--tint-50)',
                100: 'var(--tint-100)',
                200: 'var(--tint-200)',
                300: 'var(--tint-300)',
                400: 'var(--tint-400)',
                500: 'var(--tint-500)',
                600: 'var(--tint-600)',
                700: 'var(--tint-700)',
                800: 'var(--tint-800)',
                900: 'var(--tint-900)',
                purple: 'var(--tint-purple)',
            },
        },
        extend: {
            borderWidth: {
                3: '3px',
            },
            boxShadow: {
                sm: '0 2px 0 var(--tint-50)',
                default: '0 2px 0 var(--tint-100), 2px 4px 0 var(--tint-50)',
                lg: '0 2px 0 var(--tint-200), 2px 4px 0 var(--tint-100), 4px 6px 0 var(--tint-50)',
                input: 'inset 0 2px 0 var(--tint-100)',
                select: 'inset 0 -2px 0 var(--tint-100)',
                focus: '0 2px 0 var(--tint-purple)',
                stack:
                    '0 4px 0 -2px var(--gray-100), 0 4px 0 -1px var(--gray-200), 0 9px 0 -4px var(--gray-100), 0 9px 0 -3px var(--gray-200)',
            },
            inset: {
                full: '100%',
            },
            width: {
                56: '14rem',
                64: '16rem',
                72: '18rem',
            },
            maxWidth: {
                40: '10rem',
                56: '14rem',
                64: '17rem',
                '7xl': '80rem',
            },
            minHeight: {
                6: '1.5rem',
                8: '2rem',
                10: '2.5rem',
                12: '3rem',
                16: '4rem',
                full: '100%',
            },
            minWidth: {
                4: '1rem',
                6: '1.5rem',
                8: '2rem',
                10: '2.5rem',
                12: '3rem',
                16: '4rem',
                48: '12rem',
                56: '14rem',
            },
            zIndex: {
                1: '1',
                60: '60',
            },
            leading: {
                tight: '1.1',
            },
            letterSpacing: {
                widest: '.15em',
            },
        },
    },
    variants: {
        display: ['responsive', 'group-hover'],
        opacity: ['group-hover', 'hover'],
    },
};
